name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
    - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.x']
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make setup
    - name: Run linting & tests
      run:  make test
